---

###
# GRAFANA
###

# Version
grafana_version: 7.0.0

# Directories
grafana_data_dir: /var/lib/grafana
grafana_plugin_dir: /var/lib/grafana/plugins

# User
grafana_user_id: "472" # Grafana user id in Docker

###
# DOCKER
###

# Network
grafana_docker_network:
  name: grafana
  state: present

# Stack
grafana_docker:
  env:
    GF_INSTALL_PLUGINS: "https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/download/v0.3/novatec-service-dependency-graph-panel.zip;novatec-service-dependency-graph-panel"
  name: grafana
  image: grafana/grafana:{{ grafana_version }}
  state: started
  network: grafana
  ports:
    - 3000:3000
  volumes:
    - "{{ grafana_data_dir }}:/var/lib/grafana"
    - "{{ grafana_plugin_dir }}:/var/lib/grafana/plugins"
